#!/usr/bin/env python3
"""Regenerate recipes/catalog.md and recipes/index.json from recipe frontmatter.

Run after adding or editing any recipe, and commit the generated files
together with your change (see AGENT.md).

Usage:
    python3 tools/catalog.py
"""
from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict

from recipe_lib import RECIPES_DIR, load_all_recipes

CATALOG_PATH = RECIPES_DIR / "catalog.md"
INDEX_PATH = RECIPES_DIR / "index.json"

INDEX_FIELDS = [
    "id", "title", "cuisine", "category", "servings", "prep_time", "cook_time",
    "difficulty", "tags", "status", "image", "source", "nutrition", "created", "updated",
]


def total_minutes(meta: dict) -> int:
    return int(meta.get("prep_time") or 0) + int(meta.get("cook_time") or 0)


def build_index(recipes: list[dict]) -> list[dict]:
    entries = []
    for recipe in recipes:
        meta = recipe["meta"]
        entry = {field: meta.get(field) for field in INDEX_FIELDS if meta.get(field) not in (None, "")}
        entry["slug"] = recipe["slug"]
        entry["file"] = recipe["path"].name
        entries.append(entry)
    return sorted(entries, key=lambda e: e["title"].lower())


def build_catalog(recipes: list[dict]) -> str:
    published = [r for r in recipes if r["meta"].get("status") == "published"]
    drafts = [r for r in recipes if r["meta"].get("status") != "published"]

    lines: list[str] = []
    lines.append("# Recipe Catalog")
    lines.append("")
    lines.append("> Generated by `tools/catalog.py` — do not edit by hand.")
    lines.append("")
    lines.append(f"**{len(published)} published** · {len(drafts)} draft(s) · "
                 f"{len(recipes)} total")
    lines.append("")

    if recipes:
        categories = Counter(r["meta"].get("category", "other") for r in published)
        lines.append("**By category:** " + " · ".join(
            f"{cat} {n}" for cat, n in sorted(categories.items())) or "none yet")
        lines.append("")

    by_cuisine: dict[str, list[dict]] = defaultdict(list)
    for recipe in sorted(published, key=lambda r: r["meta"]["title"].lower()):
        by_cuisine[recipe["meta"].get("cuisine", "other")].append(recipe)

    for cuisine in sorted(by_cuisine):
        lines.append(f"## {cuisine.replace('-', ' ').title()}")
        lines.append("")
        lines.append("| Recipe | Category | Servings | Total (min) | Difficulty | Tags |")
        lines.append("|---|---|---|---|---|---|")
        for recipe in by_cuisine[cuisine]:
            meta = recipe["meta"]
            tags = ", ".join(f"`{t}`" for t in meta.get("tags", []))
            lines.append(
                f"| [{meta['title']}]({recipe['path'].name}) "
                f"| {meta['category']} | {meta['servings']} | {total_minutes(meta)} "
                f"| {meta['difficulty']} | {tags} |"
            )
        lines.append("")

    if drafts:
        lines.append("## Drafts (in progress)")
        lines.append("")
        for recipe in sorted(drafts, key=lambda r: r["meta"]["title"].lower()):
            meta = recipe["meta"]
            lines.append(f"- [{meta['title']}]({recipe['path'].name}) — {meta.get('cuisine', '?')}")
        lines.append("")

    lines.append("Legend: tags follow the vocabulary in `docs/data-model.md`; "
                 "`quick` = prep + cook ≤ 30 min.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    recipes, failures = load_all_recipes(verbose=False)
    if failures:
        for failure in failures:
            print(f"  unparseable: {failure['path'].name}: {failure['error']}", file=sys.stderr)
        print("error: fix unparseable files before generating the catalog", file=sys.stderr)
        return 1

    CATALOG_PATH.write_text(build_catalog(recipes), encoding="utf-8")
    INDEX_PATH.write_text(json.dumps(build_index(recipes), indent=2, ensure_ascii=False) + "\n",
                          encoding="utf-8")

    cuisines = sorted({r["meta"].get("cuisine", "other") for r in recipes})
    print(f"Catalog written:  {CATALOG_PATH}")
    print(f"Index written:    {INDEX_PATH}")
    print(f"Recipes indexed:  {len(recipes)} "
          f"({sum(1 for r in recipes if r['meta'].get('status') == 'published')} published, "
          f"{sum(1 for r in recipes if r['meta'].get('status') != 'published')} draft)")
    print(f"Cuisines covered: {', '.join(cuisines) if cuisines else 'none yet'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
